<a href="https://colab.research.google.com/github/tinemyumi/saude-mental-datasus/blob/main/notebooks/3_tratamento_dados_sihsus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Relatório Detalhado de Alterações**

**Integrantes**
- Larissa Yumi Tinem
- Leo Tsuchida Hoçoya

**Conteúdo:**
- Acesso aos dados no Google Drive, análise exploratória inicial como verificação de dados nulos e duplicados.

**Histórico de Alterações**
- **13/09/2025** - Larissa Tinem - Criação do arquivo, acesso dos dados no Google Drive, realização da análise exploratória inicial
- **26/09/2025** - Larissa Tinem - Ajustes nos comentários e na organização do projeto.
- **08/10/2025** - Larissa Tinem - Acréscimo de outras colunas no DataFrame (df_saude_mental).
- **20/03/2026** - Larissa Tinem - Ajuste final do notebook

In [10]:
# Instale as bibliotecas necessárias
!pip install pandas
!pip install pyarrow

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

# **Conectando-se ao Google Drive**

In [11]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

# **Acessando dados no Google Drive**

Data: 13/09/2025 Autor: Larissa Tinem

In [2]:
# Código para acessar os dados no Google Drive

import pandas as pd
import os
import importlib
import sys

# Define o caminho da pasta onde os arquivos estão salvos no Google Drive
caminho_dados_drive = '/content/drive/MyDrive/Dataframes'

# Verifica se a pasta existe para evitar erros
if os.path.exists(caminho_dados_drive):
    print("A pasta foi encontrada no Google Drive. Listando arquivos...")

    # Lista todos os arquivos na pasta para visualização
    arquivos_na_pasta = os.listdir(caminho_dados_drive)
    print(arquivos_na_pasta)

else:
    print("Erro: A pasta de dados não foi encontrada. Verifique se o caminho está correto.")

print("\nProcesso concluído!")

A pasta foi encontrada no Google Drive. Listando arquivos...
['cod_regioes.csv', 'df_pre_pandemia.parquet', 'df_pandemia.parquet', 'df_pos_pandemia.parquet', 'macroregiao_de_saude.csv', 'codigos_municipios_regioes.csv', 'df_sih_sus_tratado']

Processo concluído!

# **1. Análise Inicial do Dataset Pré-Pandemia**

Data: 13/09/2025 Autor: Larissa Tinem

## **1.1. Filtrando dados sobre saúde mental no Estado de São Paulo e transformação de dados**

- Os códigos CID-10 para transtornos mentais e comportamentais variam de F00 a F99.
- Código para o estado de São Paulo = 35
- Transformação de tipos de dados

**Alterações**

- Data: 20/09/2025 Autor: Larissa Tinem
- Data: 08/10/2025 Autor: Larissa Tinem - Acréscimo de outras colunas
- Data: 27/01/2026 Autor: Larissa Tinem - Filtragem de colunas para df do período pré-pandemia

In [3]:
# Carregando o arquivo em um dataframe
df_pre_pandemia = pd.read_parquet(
    '/content/drive/MyDrive/Dataframes/df_pre_pandemia.parquet',
    columns=[
      'N_AIH',
      'UF_ZI',
      'IDENT',
      'ANO_CMPT',
      'MES_CMPT',
      'NASC',
      'IDADE',
      'SEXO',
      'RACA_COR',
      'ESPEC',
      'MUNIC_RES',
      'CEP',
      'DIAG_PRINC',
      'DIAG_SECUN',
      'CAR_INT',
      'COBRANCA',
      'MUNIC_MOV',
      'CID_ASSO',
      'CID_MORTE',
      'COMPLEX',
      'DT_INTER',
      'DT_SAIDA',
      'QT_DIARIAS',
      'DIAS_PERM',
      'MORTE']
)

In [4]:
# Dados sobre saúde mental (CID-10 F00-F99)
df_saude_mental_pre = df_pre_pandemia[df_pre_pandemia['DIAG_PRINC'].str.startswith('F', na=False)].copy()
# Internações do estado de São Paulo (código 35)
df_saude_mental_pre = df_saude_mental_pre[df_saude_mental_pre['UF_ZI'].str.startswith('35', na=False)].copy()

## **1.2. Transformação dos tipos de dados**

- Conversão das colunas **NASC, DT_INTER e DT_SAIDA** para formato data (aaaammdd)
- Conversão das colunas **ANO_CMPT, MES_CMPT, IDADE, QT_DIARIAS, DIAS_PERM** para números inteiros

Data: 20/09/2025 Autor: Larissa Tinem - Conversão de tipos de dados

In [5]:
import importlib

# Transformação dos tipos de dados

# Conversão para formato de data
df_saude_mental_pre['DT_INTER'] = pd.to_datetime(df_saude_mental_pre['DT_INTER'])
df_saude_mental_pre['DT_SAIDA'] = pd.to_datetime(df_saude_mental_pre['DT_SAIDA'])
df_saude_mental_pre['NASC'] = pd.to_datetime(df_saude_mental_pre['NASC'])

# Conversão para int
conversao_int = ['ANO_CMPT', 'MES_CMPT', 'IDADE', 'QT_DIARIAS', 'DIAS_PERM']
for coluna in conversao_int:
    df_saude_mental_pre[coluna] = df_saude_mental_pre[coluna].astype(int)

In [6]:
df_saude_mental_pre.head()

,N_AIH,UF_ZI,IDENT,ANO_CMPT,MES_CMPT,NASC,IDADE,SEXO,RACA_COR,ESPEC,...,COBRANCA,MUNIC_MOV,CID_ASSO,CID_MORTE,COMPLEX,DT_INTER,DT_SAIDA,QT_DIARIAS,DIAS_PERM,MORTE
696,3514126960003,351880,1,2015,1,1971-10-30,43,3,01,05,...,12,351880,0000,0000,02,2014-12-28,2014-12-31,3,3,0
697,3514126960179,351880,1,2015,1,1972-03-05,42,1,99,05,...,12,351880,0000,0000,02,2014-12-16,2014-12-20,4,4,0
698,3514126960180,351880,1,2015,1,1972-09-25,42,3,99,05,...,12,351880,0000,0000,02,2014-12-29,2015-01-05,7,7,0
699,3514126960300,351880,1,2015,1,1976-04-06,38,1,03,05,...,12,351880,0000,0000,02,2014-12-30,2015-01-06,7,7,0
700,3515101701397,351880,1,2015,1,1996-02-20,18,3,03,05,...,12,351880,0000,0000,02,2015-01-01,2015-01-03,2,2,0

## **1.3. Salvando DF de saúde mental no Google Drive**

In [7]:
df_saude_mental_pre.to_parquet('/content/drive/MyDrive/Dataframes/df_sih_sus_tratado/saude_mental_pre_pandemia.parquet')

## **1.4. Análise Exploratória do Dataset De Estudo Pré-Pandemia**

Para esta etapa, selecionamos apenas as colunas de interesse do dataset original relacionadas à saúde mental e às características demográficas e clínicas dos pacientes.
A análise a seguir será realizada apenas nesse subconjunto, visando explorar padrões de internação, duração das internações e distribuição demográfica dos pacientes.

Data: 08/10/2025 Autor: Larissa Tinem

In [8]:
# Informações sobre tipos de dado e quantidade de linhas e colunas
df_saude_mental_pre.info()

<class 'pandas.core.frame.DataFrame'>
Index: 556336 entries, 696 to 12626596
Data columns (total 25 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   N_AIH       556336 non-null  object
 1   UF_ZI       556336 non-null  object
 2   IDENT       556336 non-null  object
 3   ANO_CMPT    556336 non-null  int64
 4   MES_CMPT    556336 non-null  int64
 5   NASC        556336 non-null  datetime64[ns]
 6   IDADE       556336 non-null  int64
 7   SEXO        556336 non-null  object
 8   RACA_COR    556336 non-null  object
 9   ESPEC       556336 non-null  object
 10  MUNIC_RES   556336 non-null  object
 11  CEP         556336 non-null  object
 12  DIAG_PRINC  556336 non-null  object
 13  DIAG_SECUN  556336 non-null  object
 14  CAR_INT     556336 non-null  object
 15  COBRANCA    556336 non-null  object
 16  MUNIC_MOV   556336 non-null  object
 17  CID_ASSO    556336 non-null  object
 18  CID_MORTE   556336 non-null  object
 19  COMPLEX     556336 non-null  object
 20  DT_INTER    556336 non-null  datetime64[ns]
 21  DT_SAIDA    556336 non-null  datetime64[ns]
 22  QT_DIARIAS  556336 non-null  int64
 23  DIAS_PERM   556336 non-null  int64
 24  MORTE       556336 non-null  object
dtypes: datetime64[ns](3), int64(5), object(17)
memory usage: 110.4+ MB

In [9]:
# Informações sobre valores ausentes
df_saude_mental_pre.isna().sum()

N_AIH         0
UF_ZI         0
IDENT         0
ANO_CMPT      0
MES_CMPT      0
NASC          0
IDADE         0
SEXO          0
RACA_COR      0
ESPEC         0
MUNIC_RES     0
CEP           0
DIAG_PRINC    0
DIAG_SECUN    0
CAR_INT       0
COBRANCA      0
MUNIC_MOV     0
CID_ASSO      0
CID_MORTE     0
COMPLEX       0
DT_INTER      0
DT_SAIDA      0
QT_DIARIAS    0
DIAS_PERM     0
MORTE         0
dtype: int64

In [25]:
# Informações sobre valores duplicados
duplicadas = df_saude_mental_pre.duplicated().sum()
print(duplicadas)

0

# **2. Análise Exploratória do Dataset Pandemia**

Data: 13/09/2025 Autor: Larissa Tinem

## **2.1. Filtrando dados sobre saúde mental no Estado de São Paulo e transformação de dados**

- Os códigos CID-10 para transtornos mentais e comportamentais variam de F00 a F99.
- Código para o estado de São Paulo = 35
- Transformação de tipos de dados

**Alterações**

- Data: 20/09/2025 Autor: Larissa Tinem
- Data: 08/10/2025 Autor: Larissa Tinem - Acréscimo de outras colunas
- Data: 27/01/2026 Autor: Larissa Tinem - Filtragem de colunas para df do período da pandemia

In [16]:
# Carregando o arquivo em um dataframe
df_pandemia = pd.read_parquet(
    '/content/drive/MyDrive/Dataframes/df_pandemia.parquet',
    columns=[
      'N_AIH',
      'UF_ZI',
      'IDENT',
      'ANO_CMPT',
      'MES_CMPT',
      'NASC',
      'IDADE',
      'SEXO',
      'RACA_COR',
      'ESPEC',
      'MUNIC_RES',
      'CEP',
      'DIAG_PRINC',
      'DIAG_SECUN',
      'CAR_INT',
      'COBRANCA',
      'MUNIC_MOV',
      'CID_ASSO',
      'CID_MORTE',
      'COMPLEX',
      'DT_INTER',
      'DT_SAIDA',
      'QT_DIARIAS',
      'DIAS_PERM',
      'MORTE']
)

In [17]:
# Dados sobre saúde mental (CID-10 F00-F99)
df_saude_mental_pandemia = df_pandemia[df_pandemia['DIAG_PRINC'].str.startswith('F', na=False)].copy()
# Internações do estado de São Paulo (código 35)
df_saude_mental_pandemia = df_saude_mental_pandemia[df_saude_mental_pandemia['UF_ZI'].str.startswith('35', na=False)].copy()

## **2.2. Transformação dos tipos de dados**

- Conversão das colunas **NASC, DT_INTER e DT_SAIDA** para formato data (aaaammdd)
- Conversão das colunas **ANO_CMPT, MES_CMPT, IDADE, QT_DIARIAS, DIAS_PERM** para números inteiros

Data: 20/09/2025 Autor: Larissa Tinem - Conversão de tipos de dados

In [18]:
import importlib

# Transformação dos tipos de dados

# Conversão para formato de data
df_saude_mental_pandemia['DT_INTER'] = pd.to_datetime(df_saude_mental_pandemia['DT_INTER'])
df_saude_mental_pandemia['DT_SAIDA'] = pd.to_datetime(df_saude_mental_pandemia['DT_SAIDA'])
df_saude_mental_pandemia['NASC'] = pd.to_datetime(df_saude_mental_pandemia['NASC'])

# Conversão para int
conversao_int = ['ANO_CMPT', 'MES_CMPT', 'IDADE', 'QT_DIARIAS', 'DIAS_PERM']
for coluna in conversao_int:
    df_saude_mental_pandemia[coluna] = df_saude_mental_pandemia[coluna].astype(int)

In [19]:
df_saude_mental_pandemia.head()

,N_AIH,UF_ZI,IDENT,ANO_CMPT,MES_CMPT,NASC,IDADE,SEXO,RACA_COR,ESPEC,...,COBRANCA,MUNIC_MOV,CID_ASSO,CID_MORTE,COMPLEX,DT_INTER,DT_SAIDA,QT_DIARIAS,DIAS_PERM,MORTE
233,3519103031378,350000,1,2020,1,1998-05-17,21,1,01,05,...,15,350950,0000,0000,02,2019-12-21,2019-12-22,1,1,0
234,3520104129982,350000,1,2020,1,1990-04-07,29,1,01,05,...,12,350950,0000,0000,02,2020-01-02,2020-01-04,2,2,0
235,3520104130114,350000,1,2020,1,1978-09-20,41,1,02,05,...,12,350950,0000,0000,02,2019-12-30,2020-01-02,3,3,0
236,3520104130499,350000,1,2020,1,1975-11-19,44,3,01,05,...,15,350950,0000,0000,02,2019-12-31,2020-01-10,10,10,0
237,3520104130785,350000,1,2020,1,1999-05-06,20,1,01,05,...,15,350950,0000,0000,02,2019-10-01,2019-10-11,10,10,0

## **2.3. Salvando DF de saúde mental no Google Drive**

In [20]:

df_saude_mental_pandemia.to_parquet('/content/drive/MyDrive/Dataframes/df_sih_sus_tratado/saude_mental_pandemia.parquet')

## **2.4. Análise Exploratória do Dataset De Estudo Pré-Pandemia**

Para esta etapa, selecionamos apenas as colunas de interesse do dataset original relacionadas à saúde mental e às características demográficas e clínicas dos pacientes.
A análise a seguir será realizada apenas nesse subconjunto, visando explorar padrões de internação, duração das internações e distribuição demográfica dos pacientes.

Data: 08/10/2025 Autor: Larissa Tinem

In [21]:
# Informações sobre tipos de dado e quantidade de linhas e colunas
df_saude_mental_pandemia.info()

<class 'pandas.core.frame.DataFrame'>
Index: 241285 entries, 233 to 7177799
Data columns (total 25 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   N_AIH       241285 non-null  object
 1   UF_ZI       241285 non-null  object
 2   IDENT       241285 non-null  object
 3   ANO_CMPT    241285 non-null  int64
 4   MES_CMPT    241285 non-null  int64
 5   NASC        241285 non-null  datetime64[ns]
 6   IDADE       241285 non-null  int64
 7   SEXO        241285 non-null  object
 8   RACA_COR    241285 non-null  object
 9   ESPEC       241285 non-null  object
 10  MUNIC_RES   241285 non-null  object
 11  CEP         241285 non-null  object
 12  DIAG_PRINC  241285 non-null  object
 13  DIAG_SECUN  241285 non-null  object
 14  CAR_INT     241285 non-null  object
 15  COBRANCA    241285 non-null  object
 16  MUNIC_MOV   241285 non-null  object
 17  CID_ASSO    241285 non-null  object
 18  CID_MORTE   241285 non-null  object
 19  COMPLEX     241285 non-null  object
 20  DT_INTER    241285 non-null  datetime64[ns]
 21  DT_SAIDA    241285 non-null  datetime64[ns]
 22  QT_DIARIAS  241285 non-null  int64
 23  DIAS_PERM   241285 non-null  int64
 24  MORTE       241285 non-null  object
dtypes: datetime64[ns](3), int64(5), object(17)
memory usage: 47.9+ MB

In [22]:
# Informações sobre valores ausentes
df_saude_mental_pandemia.isna().sum()

N_AIH         0
UF_ZI         0
IDENT         0
ANO_CMPT      0
MES_CMPT      0
NASC          0
IDADE         0
SEXO          0
RACA_COR      0
ESPEC         0
MUNIC_RES     0
CEP           0
DIAG_PRINC    0
DIAG_SECUN    0
CAR_INT       0
COBRANCA      0
MUNIC_MOV     0
CID_ASSO      0
CID_MORTE     0
COMPLEX       0
DT_INTER      0
DT_SAIDA      0
QT_DIARIAS    0
DIAS_PERM     0
MORTE         0
dtype: int64

In [24]:
# Informações sobre valores duplicados
duplicadas = df_saude_mental_pandemia.duplicated().sum()
print(duplicadas)

0

# **3. Análise Exploratória do Dataset Pós-Pandemia**

Data: 13/09/2025 Autor: Larissa Tinem

## **3.1. Filtrando dados sobre saúde mental no Estado de São Paulo e transformação de dados**

- Os códigos CID-10 para transtornos mentais e comportamentais variam de F00 a F99.
- Código para o estado de São Paulo = 35
- Transformação de tipos de dados

**Alterações**

- Data: 20/09/2025 Autor: Larissa Tinem
- Data: 08/10/2025 Autor: Larissa Tinem - Acréscimo de outras colunas
- Data: 27/01/2026 Autor: Larissa Tinem - Filtragem de colunas para df do período pandemia

In [26]:
# Carregando o arquivo em um dataframe
df_pos_pandemia = pd.read_parquet(
    '/content/drive/MyDrive/Dataframes/df_pos_pandemia.parquet',
    columns=[
      'N_AIH',
      'UF_ZI',
      'IDENT',
      'ANO_CMPT',
      'MES_CMPT',
      'NASC',
      'IDADE',
      'SEXO',
      'RACA_COR',
      'ESPEC',
      'MUNIC_RES',
      'CEP',
      'DIAG_PRINC',
      'DIAG_SECUN',
      'CAR_INT',
      'COBRANCA',
      'MUNIC_MOV',
      'CID_ASSO',
      'CID_MORTE',
      'COMPLEX',
      'DT_INTER',
      'DT_SAIDA',
      'QT_DIARIAS',
      'DIAS_PERM',
      'MORTE']
)

## **3.2. Transformação dos tipos de dados**

- Conversão das colunas **NASC, DT_INTER e DT_SAIDA** para formato data (aaaammdd)
- Conversão das colunas **ANO_CMPT, MES_CMPT, IDADE, QT_DIARIAS, DIAS_PERM** para números inteiros

Data: 20/09/2025 Autor: Larissa Tinem - Conversão de tipos de dados

In [27]:
# Dados sobre saúde mental (CID-10 F00-F99)
df_saude_mental_pos = df_pos_pandemia[df_pos_pandemia['DIAG_PRINC'].str.startswith('F', na=False)].copy()
# Internações do estado de São Paulo (código 35)
df_saude_mental_pos = df_saude_mental_pos[df_saude_mental_pos['UF_ZI'].str.startswith('35', na=False)].copy()

In [28]:
import importlib

# Transformação dos tipos de dados

# Conversão para formato de data
df_saude_mental_pos['DT_INTER'] = pd.to_datetime(df_saude_mental_pos['DT_INTER'])
df_saude_mental_pos['DT_SAIDA'] = pd.to_datetime(df_saude_mental_pos['DT_SAIDA'])
df_saude_mental_pos['NASC'] = pd.to_datetime(df_saude_mental_pos['NASC'])

# Conversão para int
conversao_int = ['ANO_CMPT', 'MES_CMPT', 'IDADE', 'QT_DIARIAS', 'DIAS_PERM']
for coluna in conversao_int:
    df_saude_mental_pos[coluna] = df_saude_mental_pos[coluna].astype(int)

In [29]:
df_saude_mental_pos.head()

,N_AIH,UF_ZI,IDENT,ANO_CMPT,MES_CMPT,NASC,IDADE,SEXO,RACA_COR,ESPEC,...,COBRANCA,MUNIC_MOV,CID_ASSO,CID_MORTE,COMPLEX,DT_INTER,DT_SAIDA,QT_DIARIAS,DIAS_PERM,MORTE
130,3522120931538,350000,1,2023,1,1995-05-30,27,1,03,05,...,12,355030,0000,0000,02,2022-12-28,2023-01-02,5,5,0
131,3522120931934,350000,1,2023,1,1987-04-30,35,3,01,05,...,12,355030,0000,0000,02,2022-12-12,2023-01-03,22,22,0
132,3522120931956,350000,1,2023,1,1976-09-12,46,1,02,05,...,12,355030,0000,0000,02,2022-12-25,2023-01-03,9,9,0
133,3522120931967,350000,1,2023,1,1991-02-05,31,1,02,05,...,12,355030,0000,0000,02,2022-12-28,2023-01-03,6,6,0
248,3522120931494,350000,1,2023,1,1991-11-24,31,1,02,05,...,12,355030,0000,0000,02,2022-12-24,2023-01-02,9,9,0

## **3.3. Salvando DF de saúde mental no Google Drive**

In [30]:
df_saude_mental_pos.to_parquet('/content/drive/MyDrive/Dataframes/df_sih_sus_tratado/saude_mental_pos_pandemia.parquet')

## **3.4. Análise Exploratória do Dataset De Estudo Pós-Pandemia**

Para esta etapa, selecionamos apenas as colunas de interesse do dataset original relacionadas à saúde mental e às características demográficas e clínicas dos pacientes.
A análise a seguir será realizada apenas nesse subconjunto, visando explorar padrões de internação, duração das internações e distribuição demográfica dos pacientes.

Data: 08/10/2025 Autor: Larissa Tinem

In [31]:
# Informações sobre tipos de dado e quantidade de linhas e colunas
df_saude_mental_pos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 282049 entries, 130 to 8476020
Data columns (total 25 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   N_AIH       282049 non-null  object
 1   UF_ZI       282049 non-null  object
 2   IDENT       282049 non-null  object
 3   ANO_CMPT    282049 non-null  int64
 4   MES_CMPT    282049 non-null  int64
 5   NASC        282049 non-null  datetime64[ns]
 6   IDADE       282049 non-null  int64
 7   SEXO        282049 non-null  object
 8   RACA_COR    282049 non-null  object
 9   ESPEC       282049 non-null  object
 10  MUNIC_RES   282049 non-null  object
 11  CEP         282049 non-null  object
 12  DIAG_PRINC  282049 non-null  object
 13  DIAG_SECUN  282049 non-null  object
 14  CAR_INT     282049 non-null  object
 15  COBRANCA    282049 non-null  object
 16  MUNIC_MOV   282049 non-null  object
 17  CID_ASSO    282049 non-null  object
 18  CID_MORTE   282049 non-null  object
 19  COMPLEX     282049 non-null  object
 20  DT_INTER    282049 non-null  datetime64[ns]
 21  DT_SAIDA    282049 non-null  datetime64[ns]
 22  QT_DIARIAS  282049 non-null  int64
 23  DIAS_PERM   282049 non-null  int64
 24  MORTE       282049 non-null  object
dtypes: datetime64[ns](3), int64(5), object(17)
memory usage: 55.9+ MB

In [32]:
# Informações sobre valores ausentes
df_saude_mental_pos.isna().sum()

N_AIH         0
UF_ZI         0
IDENT         0
ANO_CMPT      0
MES_CMPT      0
NASC          0
IDADE         0
SEXO          0
RACA_COR      0
ESPEC         0
MUNIC_RES     0
CEP           0
DIAG_PRINC    0
DIAG_SECUN    0
CAR_INT       0
COBRANCA      0
MUNIC_MOV     0
CID_ASSO      0
CID_MORTE     0
COMPLEX       0
DT_INTER      0
DT_SAIDA      0
QT_DIARIAS    0
DIAS_PERM     0
MORTE         0
dtype: int64

In [33]:
# Informações sobre valores duplicados
duplicadas = df_saude_mental_pos.duplicated().sum()
print(duplicadas)

0